### ISSUE TITLE
Option to disable "Listed buffers are included in the set of potential counterparts"

### ISSUE THREAD

**Issue by noscript** [jpetrie/vim-counterpoint#12]
I couldn't find how to disable that. First of all it picks wrong buffer with only barely related file name, and second - it doesn't even try to load the right file from the disk.

**Comment by jpetrie** [comment]
> I couldn't find how to disable that.

That's right, you can't. I'll add a global toggle for it.

> First of all it picks wrong buffer with only barely related file name, and second - it doesn't even try to load the right file from the disk.

This sounds like a bug though. Can you provide more information about what files you expected it to have picked and which it ended up picking (in here or in another bug, whichever you prefer)?

**Comment by noscript** [comment]
I have 3 files in a directory:
* `file.h`
* `file.cpp`
* `other_file.cpp`

I open `other_file.cpp` and `file.h`, current buffer is `file.h`. I do `:CounterpointNext` expecting to get to `file.cpp`, but it switches to `other_file.cpp`. I do `:CounterpointNext` again, hoping to get back to `file.cpp`, but it fails with `No counterpart available.`

**Comment by jpetrie** [comment]
https://github.com/jpetrie/vim-counterpoint/commit/7830a8b66ccc11c2e42d8a25645a1765964068f6 (also tagged as 1.4) should address this for you. It reverts the plugin back to the default behavior prior to the commit that added the "include listed" feature, and lets you opt-in to including listed buffers via `g:counterpoint_include_listed = 1` in your configuration files. For your use case you shouldn't need to configure anything.

I'll look into the behavior you reported, as that's decidedly not intentional.

**Comment by noscript** [comment]
Thanks!

**Comment by noscript** [comment]
Or actually, since you still will fix the behavior, reopened.

**Comment by jpetrie** [comment]
https://github.com/jpetrie/vim-counterpoint/commit/27a433f1020eaa0b27de3abbaf6de27630a85d7d should address the incorrect behavior; the problem was that I was using a regex that did not correctly make sure the potential listed buffer matched the current file name, it just needed to end with the current file name.

There's probably still a bug in here where the listed scan is not respecting `g:counterpoint_search_depth` but I'll track that on its own.
